#!/bin/sh

FORGE_PATH=THE_INSTALL_PATH

# For prototype mode, we'll restart Forge if it's config file or source code
# change.
RUN_CMD="${FORGE_PATH}/node_modules/.bin/nodemon -w ./forge.config.js -w ${FORGE_PATH}/build"

if [ "${1}" != "prototype" -a "${1}" != "" ]; then
  RUN_CMD=node
fi

${RUN_CMD} ${FORGE_PATH} "${@}"
