#!/bin/sh

# create directories
mkdir {assets,includes,layouts,src}

# write default forge config file
cat << EOF > forge.config.js
module.exports = {
  metadata: {

  },
  dirs: {
    source: './src',
    assets: './assets',
    layouts: './layouts',
    includes: './includes',
    build: './build'
  }
}
EOF

# create main CSS file
mkdir -p src/css
cat << EOF > src/css/main.css
@tailwind preflight;

@tailwind components;

/* components */

@tailwind utilities;
EOF

# write default page layout
cat << EOF > layouts/basepage.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- <meta name="description" content=""> -->
    <!-- NOTE: Google doesn't use the meta keywords... -->

    <!-- CSS -->
    <link rel="stylesheet" href="/css/main.css" type="text/css">

    <title><%= title %> - <%= site.title %></title>
  </head>

  <body class='relative flex flex-col min-h-screen'>

    <header class='container mx-auto'>

    </header>

    <div class='flex-1'>
      <%- contents %>
    </div>

    <footer class='container mx-auto pin-b'>

    </footer>

  </body>
</html>
EOF

# create gitignore
echo "**/*.DS_Store" >> .gitignore
echo build/ >> .gitignore
