#!/bin/sh

say () {
  echo "\n\033[1;34m# ${1}\033[0;37m\n"
}

set -e
# any subsequent commands that fail will cause the script to stop


say "Installing starter script"

# install jigs bootstrap script
CMD="s+THE_INSTALL_PATH+${PWD}+"

# either the first argument or ~/.bin
USER_BIN=${1:-${HOME}/.bin}
JIGS_FILE=${USER_BIN}/jigs
mkdir -p ${USER_BIN}/

cat ./jigs | sed ${CMD} > ${JIGS_FILE}
chmod +x ${JIGS_FILE}

echo "...done"

say "Jigs installed"
echo "make sure ${USER_BIN} is in your PATH"
