#!/bin/sh

# clean up
rm -rf built-forge
# copy all these files so they are available to the docker build context
mkdir -p built-forge/build
cp -r ../build built-forge/
cp -r ../{package*.json,configs,install-forge,forge} built-forge/

# build container
docker build -t forge-int-test .
